BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "test" (
	"field1"	TEXT,
	"field2"	TEXT,
	"field3"	TEXT,
	"field4"	TEXT,
	"field5"	TEXT,
	"field6"	TEXT,
	"field7"	TEXT,
	"field8"	TEXT,
	"field9"	TEXT,
	"field10"	TEXT,
	"field11"	TEXT,
	"field12"	TEXT,
	"field13"	TEXT,
	"field14"	TEXT,
	"field15"	TEXT,
	"field16"	TEXT,
	"field17"	TEXT,
	"field18"	TEXT,
	"field19"	TEXT,
	"field20"	TEXT,
	"field21"	TEXT,
	"field22"	TEXT
);
INSERT INTO "test" VALUES ('NO','WORD','CONST1','CONST2','ETOH1','ETOH2','ETOH3','ETOE1','ETOE2','ETOE3','EXAM1','EXAM2','EXAM2','SYNONYM1','SYNONYM2','SYNONYM3','ANTONYMS1','ANTONYMS2','ANTONYMS3','FWORD','IMG_URL','MP3_URL');
INSERT INTO "test" VALUES ('10000','abide','abode / abided','abode / abided / abidden','참다, 견디다',NULL,NULL,NULL,NULL,NULL,'She decided to abide the rules',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10001','arise','arose','arisen','무엇으로 인해 생기다, 발생하다',NULL,NULL,NULL,NULL,NULL,'He arose from the water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10002','awake','awakened / awoke','awakened / awoken','깨다, 불러일으키다',NULL,NULL,NULL,NULL,NULL,'I awoke to the sound of the alarm clock',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10003','backslide','backslid','backslidden / backslid','뒤로 내려가다',NULL,NULL,NULL,NULL,NULL,'The boy backslid on the slide',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10004','be','was/ were','been','있다, 존재하다',NULL,NULL,NULL,NULL,NULL,'Will you be my friend?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10005','bear','bore','born / borne','출생하다',NULL,NULL,NULL,NULL,NULL,'My wife bore a baby yesterday',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10006','beat','beat','beaten','치다, 때리다',NULL,NULL,NULL,NULL,NULL,'You should never beat someone',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10007','become','became','become','(무엇이) 되다',NULL,NULL,NULL,NULL,NULL,'The tree will become old and dry, if there''s not enough water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10008','begin','began','begun','시작하다',NULL,NULL,NULL,NULL,NULL,'The race will begin soon',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10009','bend','bent','bent','굽히다, 구부리다',NULL,NULL,NULL,NULL,NULL,'She bent backwards',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10010','bet','bet','bet','돈을 걸다, 내기하다',NULL,NULL,NULL,NULL,NULL,'I bet I can win this round',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10011','bid (farewell)','bade','bidden','인사를 하다, 고하다',NULL,NULL,NULL,NULL,NULL,'I bid her goodnight',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10012','bid (offer amount)','bid','bid','값을 부르다',NULL,NULL,NULL,NULL,NULL,'Are you going to bid on it, too?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10013','bind','bound','bound','묶다, 감다',NULL,NULL,NULL,NULL,NULL,'They bound his hands together tightly',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10014','bite','bit','bit/ bitten','물다',NULL,NULL,NULL,NULL,NULL,'I took a bite of the apple',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10015','bleed','bled','bled','피가 나다',NULL,NULL,NULL,NULL,NULL,'He bled from falling down the stairs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10016','blow','blew','blown','불다',NULL,NULL,NULL,NULL,NULL,'He blew on the dandelion',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10017','break','broke','broken','깨다, 부수다',NULL,NULL,NULL,NULL,NULL,'The tip of my pencil broke from pressing too hard',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10018','breed','bred','bred','번식하다',NULL,NULL,NULL,NULL,NULL,'We want to breed our dogs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10019','bring','brought','brought','가져오다',NULL,NULL,NULL,NULL,NULL,'The dog brought the bone back to the owner',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10020','broadcast','broadcast / broadcasted','broadcast / broadcasted','방송하다',NULL,NULL,NULL,NULL,NULL,'The news was broadcasted live',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10021','build','built','built','짓다, 건설하다',NULL,NULL,NULL,NULL,NULL,'The house was built over a long period of time',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10022','burn','burned / burnt','burned / burnt','태우다, 불에 타다',NULL,NULL,NULL,NULL,NULL,'The town burned down in flames',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10023','burst','burst','burst','터지다',NULL,NULL,NULL,NULL,NULL,'The planet burst solar flares',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10024','bust','busted / bust','busted / bust','부수다',NULL,NULL,NULL,NULL,NULL,'The windows got busted',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10025','buy','bought','bought','사다, 구입하다',NULL,NULL,NULL,NULL,NULL,'She bought some fruits at the market',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10026','cast','cast','cast','던지다, 걸다',NULL,NULL,NULL,NULL,NULL,'He cast the net in the sea to catch fish',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10027','catch','caught','caught','잡다',NULL,NULL,NULL,NULL,NULL,'She caught the baseball',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10028','choose','chose','chosen','선택하다, 고르다',NULL,NULL,NULL,NULL,NULL,'Harry chose to go that way',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10029','clap','clapped / clapt','clapped / clapt','박수를 치다',NULL,NULL,NULL,NULL,NULL,'They clapped at the end of the presentation',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10030','cling','clung','clung','매달리다, 달라붙다',NULL,NULL,NULL,NULL,NULL,'He clung to wall so that he wouldn''t fall',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10031','clothe','clothed / clad','clothed / clad','옷을 입히다',NULL,NULL,NULL,NULL,NULL,'Clara was clothed in fine silk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10032','come','came','come','오다',NULL,NULL,NULL,NULL,NULL,'The waiter came with our dishes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10033','cost','cost','cost','비용이 들다',NULL,NULL,NULL,NULL,NULL,'Being sick cost me a lot',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10034','creep','crept','crept','기다, 살금살금 움직이다',NULL,NULL,NULL,NULL,NULL,'The baby slowly crept to his mother',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10035','crossbreed','crossbred','crossbred','이종 교배하다',NULL,NULL,NULL,NULL,NULL,'A Bichon Poo is a crossbred dog between a Bichon and a Poodle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10036','cut','cut','cut','자르다',NULL,NULL,NULL,NULL,NULL,'She cut the strawberries in half',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10037','daydream','daydreamed / daydreamt','daydreamed / daydreamt','몽상하다 (백일몽)',NULL,NULL,NULL,NULL,NULL,'She daydreams often',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10038','deal','dealt','dealt','다루다, 논하다; 돌리다 (카드 게임에서 카드를)',NULL,NULL,NULL,NULL,NULL,'The dealer shuffled and dealt the cards',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10039','dig','dug','dug','파다',NULL,NULL,NULL,NULL,NULL,'Louis dug a hole in the soil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10040','disprove','disproved','disproved / disproven','부정하다, 틀렸음을 입증하다',NULL,NULL,NULL,NULL,NULL,'Stanley disproved the theory',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10041','dive (jump head-first)','dove / dived','dived','뛰어들다',NULL,NULL,NULL,NULL,NULL,'They dove into the role-playing game',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10042','dive (scuba diving)','dived / dove','dived','잠수하다',NULL,NULL,NULL,NULL,NULL,'Jen dove into the deep blue sea',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10043','do','did','done','~하다, 완료하다',NULL,NULL,NULL,NULL,NULL,'I''m done with my work',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10044','draw','drew','drawn','그리다',NULL,NULL,NULL,NULL,NULL,'He drew a self-portrait',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10045','dream','dreamed / dreamt','dreamed / dreamt','꿈꾸다',NULL,NULL,NULL,NULL,NULL,'She dreamed that she was a princess',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10046','drink','drank','drunk','마시다',NULL,NULL,NULL,NULL,NULL,'She drank the smoothie',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10047','drive','drove','driven','운전하다',NULL,NULL,NULL,NULL,NULL,'They drove 200 miles to visit their friends',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10048','dwell','dwelt / dwelled','dwelt / dwelled','살다; ~을 곱씹다',NULL,NULL,NULL,NULL,NULL,'I dwelled on the issue for a couple of days',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10049','eat','ate','eaten','먹다',NULL,NULL,NULL,NULL,NULL,'I ate my ice cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10050','engrave','engraved','engraved / engraven','새기다',NULL,NULL,NULL,NULL,NULL,'She engraved a heart on the tree trunk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10051','fall','fell','fallen','떨어지다',NULL,NULL,NULL,NULL,NULL,'He fell while trying to reach for the ball',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10052','feed','fed','fed','먹이다',NULL,NULL,NULL,NULL,NULL,'I fed my cat a snack',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10053','feel','felt','felt','느끼다',NULL,NULL,NULL,NULL,NULL,'She felt free in the sea',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10054','fight','fought','fought','싸우다',NULL,NULL,NULL,NULL,NULL,'The two players fought for the ball',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10055','find','found','found','찾다',NULL,NULL,NULL,NULL,NULL,'He found what he was looking for in the cabinet',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10056','fit (tailor, change size)','fitted / fit','fitted / fit','맞추다',NULL,NULL,NULL,NULL,NULL,'She needs to get fitted for new clothes after she lost weight',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10057','fit (be right size)','fit / fitted','fit / fitted','맞다, 적합하다',NULL,NULL,NULL,NULL,NULL,'The shoes fit her perfectly',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10058','flee','fled','fled','달아나다, 도망하다',NULL,NULL,NULL,NULL,NULL,'He fled the building',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10059','fling','flung','flung','내던지다',NULL,NULL,NULL,NULL,NULL,'He flung the papers at me',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10060','fly','flew','flown','날다',NULL,NULL,NULL,NULL,NULL,'He flew over the water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10061','forbid','forbade','forbidden','금지하다',NULL,NULL,NULL,NULL,NULL,'She was forbidden from entering the house',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10062','forecast','forecast','forecast','예측하다',NULL,NULL,NULL,NULL,NULL,'He forecast the sales for next year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10063','forego (also forgo)','forewent','foregone','앞서다, 앞에 가다',NULL,NULL,NULL,NULL,NULL,'He forewent her to their destination',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10064','foresee','foresaw','foreseen','예견하다',NULL,NULL,NULL,NULL,NULL,'He was able to foresee the future',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10065','foretell','foretold','foretold','예언하다',NULL,NULL,NULL,NULL,NULL,'The foretuneteller foretold my future',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10066','forget','forgot','forgotten / forgot','잊다',NULL,NULL,NULL,NULL,NULL,'He forgot to turn off the stove in the kitchen',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10067','forgive','forgave','forgiven','용서하다',NULL,NULL,NULL,NULL,NULL,'She wanted to be forgiven for her sins',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10068','forsake','forsook','forsaken','저버리다',NULL,NULL,NULL,NULL,NULL,'You should forsake your smoking habits',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10069','fraught','fraught / fraughted','fraught / fraughted','좋지 않은 것으로 가득한 (투성이의)',NULL,NULL,NULL,NULL,NULL,'She was fraught with stress',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10070','free-fall','free-fell','free-fallen','낙하하다, 높은 데서 떨어지다',NULL,NULL,NULL,NULL,NULL,'She free-fell as she went skydiving',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10071','freeze','froze','frozen','얼리다',NULL,NULL,NULL,NULL,NULL,'The snow froze and turned into icicles',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10072','frostbite','frostbit','frostbitten','동상에 걸리다',NULL,NULL,NULL,NULL,NULL,'Her nose were frostbitten',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10073','get','got','gotten / got','받다, 얻다',NULL,NULL,NULL,NULL,NULL,'I got a plant for her new house',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10074','give','gave','given','주다',NULL,NULL,NULL,NULL,NULL,'I gave a gift to my friend',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10075','go','went','gone','가다',NULL,NULL,NULL,NULL,NULL,'He went super fast on his bike',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10076','grind','ground','ground','갈다',NULL,NULL,NULL,NULL,NULL,'Did you grind the coffee beans?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10077','grow','grew','grown','자라다, 커지다',NULL,NULL,NULL,NULL,NULL,'Sprouts grew from the soil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10078','hand-feed','hand-fed','hand-fed','손으로 먹이다',NULL,NULL,NULL,NULL,NULL,'She hand-fed the animals at the zoo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10079','handwrite','handwrote','handwritten','손으로 쓰다',NULL,NULL,NULL,NULL,NULL,'The letter was handwritten',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10080','hang','hung','hung','걸다, 매달다',NULL,NULL,NULL,NULL,NULL,'The clothes were hung on the rack',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10081','have','had','had','가지다, 소유하다',NULL,NULL,NULL,NULL,NULL,'I had a pet hamster before',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10082','hear','heard','heard','듣다, 들리다',NULL,NULL,NULL,NULL,NULL,'I couldn''t hear anything with my headphones on',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10083','heave','heaved / hove','heaved / hove','들어올리다; 크게 한숨을 내쉬다',NULL,NULL,NULL,NULL,NULL,'They heaved the rope from both sides',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10084','hide','hid','hidden','감추다, 숨다',NULL,NULL,NULL,NULL,NULL,'She hid under the covers',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10085','hit','hit','hit','때리다',NULL,NULL,NULL,NULL,NULL,'She hit the ball out of the park',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10086','hold','held','held','잡고 있다, 쥐다',NULL,NULL,NULL,NULL,NULL,'The girl held on to her father''s hand',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10087','hurt','hurt','hurt','아프다',NULL,NULL,NULL,NULL,NULL,'He got hurt from falling down the stairs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10088','inlay','inlaid','inlaid','무늬를 새겨 넣다',NULL,NULL,NULL,NULL,NULL,'A design was inlaid on the pottery',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10089','input','input / inputted','input / inputted','입력하다, 투입하다',NULL,NULL,NULL,NULL,NULL,'I inputted the correct link',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10090','interbreed','interbred','interbred','상호 교배하다',NULL,NULL,NULL,NULL,NULL,'A Liger is an interbred animal between a lion and a tiger',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10091','interweave','interwove / interweaved','interwoven / interweaved','섞어 짜다',NULL,NULL,NULL,NULL,NULL,'A basket is an interwoven product of stiff fibers',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10092','interwind','interwound','interwound','얽히게 한다, 한데 감다',NULL,NULL,NULL,NULL,NULL,'The ropes were interwound on the dock',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10093','keep','kept','kept','유지하다, 계속 있다',NULL,NULL,NULL,NULL,NULL,'She kept the book to read later',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10094','kneel','knelt / kneeled','knelt / kneeled','무릎을 꿇다',NULL,NULL,NULL,NULL,NULL,'They kneeled down on the field as a sign of respect',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10095','knit','knitted / knit','knitted / knit','뜨다, 뜨개질을 하다',NULL,NULL,NULL,NULL,NULL,'I knitted a scarf',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10096','know','knew','known','알다, 이해하다',NULL,NULL,NULL,NULL,NULL,'They knew the answer to the question',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10097','lay','laid','laid','놓다, 눕히다',NULL,NULL,NULL,NULL,NULL,'The chicken laid eggs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10098','lead','led','led','이끌다, 앞장서서 안내하다',NULL,NULL,NULL,NULL,NULL,'He led the discussion',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10099','lean','leaned / leant','leaned / leant','~에 기대다',NULL,NULL,NULL,NULL,NULL,'The tower leaned to the right',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10100','leap','leaped / leapt','leaped / leapt','뛰어오르다',NULL,NULL,NULL,NULL,NULL,'The ballerina leaped on stage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10101','learn','learned / learnt','learned / learnt','배우다',NULL,NULL,NULL,NULL,NULL,'He learned by reading the textbook',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10102','leave','left','left','떠나다',NULL,NULL,NULL,NULL,NULL,'He left town by himself',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10103','lend','lent','lent','빌려주다',NULL,NULL,NULL,NULL,NULL,'I lent him my credit card',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10104','let','let','let','놓아두다, 허락하다',NULL,NULL,NULL,NULL,NULL,'The owner let the guests in the house',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10105','lie','lay','lain','눕다, 놓여 있다',NULL,NULL,NULL,NULL,NULL,'He lay down on the floor after the hard workout',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10106','lie (not tell truth) REGULAR','lied','lied','거짓말하다',NULL,NULL,NULL,NULL,NULL,'He lied about cheating on the test',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10107','light','lit / lighted','lit / lighted','(불을) 켜다',NULL,NULL,NULL,NULL,NULL,'He lighted the fireplace to warm up the living room',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10108','lip-read','lip-read','lip-read','독순법을 쓰다',NULL,NULL,NULL,NULL,NULL,'Can you lip-read?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10109','lose','lost','lost','잃어버리다',NULL,NULL,NULL,NULL,NULL,'He lost th e money in his wallet',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10110','make','made','made','만들다',NULL,NULL,NULL,NULL,NULL,'She made food for the party',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10111','mean','meant','meant','~을 뜻하다',NULL,NULL,NULL,NULL,NULL,'I wonder what she meant',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10112','meet','met','met','만나다',NULL,NULL,NULL,NULL,NULL,'We met for a study session',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10113','melt','melted','molten / melted','녹다',NULL,NULL,NULL,NULL,NULL,'The cheese melted on the sandwich',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10114','miscast','miscast','miscast','선정을 잘못하다',NULL,NULL,NULL,NULL,NULL,'They miscast the role of a solider',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10115','mischoose','mischose','mischosen','선택을 잘못하다',NULL,NULL,NULL,NULL,NULL,'I mischose the answer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10116','misdeal','misdealt','misdealt','잘못 돌리다',NULL,NULL,NULL,NULL,NULL,'The cards were misdealt',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10117','misdo','misdid','misdone','잘못 하다, 실수하다',NULL,NULL,NULL,NULL,NULL,'I will repent for what I have misdone',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10118','misgive','misgave','misgiven','의심을 품다, 염려되다',NULL,NULL,NULL,NULL,NULL,'His heart misgave him when he saw her',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10119','mishear','misheard','misheard','잘못 듣다',NULL,NULL,NULL,NULL,NULL,'He asked me to repeat what I said because he misheard the first time',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10120','mislay','mislaid','mislaid','두고 오다, 제자리에 두지 않다',NULL,NULL,NULL,NULL,NULL,'The fruit was mislaid on the stairs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10121','mislead','misled','misled','잘못 안내하다/ 인도하다/ 유인하다',NULL,NULL,NULL,NULL,NULL,'The hikers were misled by the sign',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10122','mislearn','mislearned / mislearnt','mislearned / mislearnt','잘못되게 배우다',NULL,NULL,NULL,NULL,NULL,'He mislearned the math problem',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10123','misread','misread','misread','잘못 읽다',NULL,NULL,NULL,NULL,NULL,'She misread the book, so she had to read the book all over again',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10124','misset','misset','misset','잘못 설치하다',NULL,NULL,NULL,NULL,NULL,'The technician misset the plugs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10125','misspeak','misspoke','misspoken','잘못 말하다',NULL,NULL,NULL,NULL,NULL,'He misspoke in front of her and embarrassed himself',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10126','misspell','misspelled / misspelt','misspelled / misspelt','철자를 잘못 쓰다',NULL,NULL,NULL,NULL,NULL,'Make sure to check your report for misspelled words',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10127','misspend','misspent','misspent','잘못 사용하다 (돈, 시간을)',NULL,NULL,NULL,NULL,NULL,'I misspent my money on too much online shopping',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10128','mistake','mistook','mistaken','잘못하다, 실수하다',NULL,NULL,NULL,NULL,NULL,'He mistook his words and got scammed',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10129','misteach','mistaught','mistaught','잘못 가르치다',NULL,NULL,NULL,NULL,NULL,'She mistaught the concept',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10130','misthink','misthought','misthought','잘못 생각하다',NULL,NULL,NULL,NULL,NULL,'He misthought his move',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10131','misunderstand','misunderstood','misunderstood','잘못 이해하다',NULL,NULL,NULL,NULL,NULL,'He misunderstood the homework problem',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10132','miswrite','miswrote','miswritten','잘못 쓰다',NULL,NULL,NULL,NULL,NULL,'I had to start all over again because I miswrote the essay',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10133','moonlight','moonlit','moonlit','달빛 차오르다',NULL,NULL,NULL,NULL,NULL,'I stared out into the moonlit night',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10134','mow','mowed','mowed / mown','잔디를 깍다, 베다',NULL,NULL,NULL,NULL,NULL,'I mowed the lawn the other day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10135','offset','offset','offset','상쇄하다',NULL,NULL,NULL,NULL,NULL,'The natural surroundings offset the buildings',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10136','outbid','outbid','outbid','더 비싼 값을 부르다',NULL,NULL,NULL,NULL,NULL,'The player outbid the dealer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10137','outbreed','outbred','outbred','이계 교배시키다',NULL,NULL,NULL,NULL,NULL,'The runner outdid himself by finishing the marathon',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10138','outdo','outdid','outdone','능가하다',NULL,NULL,NULL,NULL,NULL,'The concert outdrew a crowd',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10139','outdraw','outdrew','outdrawn','더 많이 끌다',NULL,NULL,NULL,NULL,NULL,'He can usually outdrink me',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10140','outdrink','outdrank','outdrunk','더 마시다',NULL,NULL,NULL,NULL,NULL,'He outdrove him at the golf range',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10141','outdrive','outdrove','outdriven','더 이끌다/ 몰다',NULL,NULL,NULL,NULL,NULL,'The boxer outfought his opponent player',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10142','outfight','outfought','outfought','더 잘 싸워 이기다',NULL,NULL,NULL,NULL,NULL,'One of the airplanes outflew the other one',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10143','outfly','outflew','outflown','~보다 더 멀리 날다',NULL,NULL,NULL,NULL,NULL,'The baby giraffee outgrew his mother',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10144','outgrow','outgrew','outgrown','~보다 더 커지자',NULL,NULL,NULL,NULL,NULL,'One of the kids outleaped his other friends',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10145','outleap','outleaped / outleapt','outleaped / outleapt','~보다 더 멀리 뛰어넘다',NULL,NULL,NULL,NULL,NULL,'The group set up the tents in the mountains and outlied in nature',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10146','outlie','outlied','outlied','밖에서 자다; 넓어지다, 퍼지다',NULL,NULL,NULL,NULL,NULL,'He outrode the other cyclist in the competition',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10147','outride','outrode','outridden','~보다 잘 타다',NULL,NULL,NULL,NULL,NULL,'She outran all the other runners during the track meet',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10148','outrun','outran','outrun','~보다 더 빠리 달리다',NULL,NULL,NULL,NULL,NULL,'He outsold the products during the promotion week',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10149','outsell','outsold','outsold','~보다 더 많이 팔다',NULL,NULL,NULL,NULL,NULL,'The main dancer outshined everyone on stage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10150','outshine','outshined / outshone','outshined / outshone','~보다 더 낫다',NULL,NULL,NULL,NULL,NULL,'He outshot his other friends at the shooting range',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10151','outshoot','outshot','outshot','~보다 잘 쏘다',NULL,NULL,NULL,NULL,NULL,'He outsung nearly everyone at the live audition',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10152','outsing','outsang','outsung','~보다 노래를 잘 부르다',NULL,NULL,NULL,NULL,NULL,'I outsat other students in the studying in the library during finals week',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10153','outsit','outsat','outsat','~보다 오래 앉아 있다',NULL,NULL,NULL,NULL,NULL,'The baby outslept his normal sleeping hours',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10154','outsleep','outslept','outslept','~보다 더 자다',NULL,NULL,NULL,NULL,NULL,'The perfumes outsmell the entire store',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10155','outsmell','outsmelled / outsmelt','outsmelled / outsmelt','~보다 강하게 냄새가 나다',NULL,NULL,NULL,NULL,NULL,'The supporter was outspoken about animal rights issues',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10156','outspeak','outspoke','outspoken','~보다 말을 잘하다, 말로 이기다',NULL,NULL,NULL,NULL,NULL,'He outsped the guys who were chasing them from behind',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10157','outspeed','outsped','outsped','~보다 더 빠르게 지나가다',NULL,NULL,NULL,NULL,NULL,'I outspent my budget during the holidays',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10158','outspend','outspent','outspent','~보다 많이 쓰다',NULL,NULL,NULL,NULL,NULL,'She outswore all of her guy friends',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10159','outswear','outswore','outsworn','~보다 심하게 욕하다',NULL,NULL,NULL,NULL,NULL,'He outswam the the other competitors and came in first place',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10160','outswim','outswam','outswum','~보다 더 빠르게 수영하다',NULL,NULL,NULL,NULL,NULL,'Robots might outthink humans in the future',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10161','outthink','outthought','outthought','~보다 더 깊이 생각하다',NULL,NULL,NULL,NULL,NULL,'The basketball player outthrew the ball across the court',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10162','outthrow','outthrew','outthrown','~보다 멀리 던지다',NULL,NULL,NULL,NULL,NULL,'I''m going to outwrite the other student by producing multiple drafts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10163','outwrite','outwrote','outwritten','~보다 많이 쓰다, 더 잘 쓰다',NULL,NULL,NULL,NULL,NULL,'I accidentally overbid on the play this round',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10164','overbid','overbid','overbid','비싸게 값을 부르다',NULL,NULL,NULL,NULL,NULL,'There are so many puppies! I think we overbred the dogs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10165','overbreed','overbred','overbred','새끼를 너무 많이 낳다',NULL,NULL,NULL,NULL,NULL,'They overbuilt the city',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10166','overbuild','overbuilt','overbuilt','지나치게 많이 짓다, 너무 대규모로 짓다',NULL,NULL,NULL,NULL,NULL,'I overbought some clothes today on my shopping spree',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10167','overbuy','overbought','overbought','너무 많이 사다',NULL,NULL,NULL,NULL,NULL,'I rode the rollercoaster to overcome my fear of heights',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10168','overcome','overcame','overcome','극복하다',NULL,NULL,NULL,NULL,NULL,'I overdid my scheduled workload',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10169','overdo','overdid','overdone','지나치게 하다, 과장하다',NULL,NULL,NULL,NULL,NULL,'I overdrew cash from the ATM machine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10170','overdraw','overdrew','overdrawn','초과 인출하다',NULL,NULL,NULL,NULL,NULL,'He''s hungover because he overdrank last night',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10171','overdrink','overdrank','overdrunk','과음하다',NULL,NULL,NULL,NULL,NULL,'He overate because he was so hungry',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10172','overeat','overate','overeaten','과식하다',NULL,NULL,NULL,NULL,NULL,'Make sure you don''t overfeed the deer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10173','overfeed','overfed','overfed','너무 많이 먹이다',NULL,NULL,NULL,NULL,NULL,'I might have overhung some bird paintings on the wall',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10174','overhang','overhung','overhung','돌출하다',NULL,NULL,NULL,NULL,NULL,'I overheard their secret',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10175','overhear','overheard','overheard','엿듣다, 우연히 듣다',NULL,NULL,NULL,NULL,NULL,'I overlay some blue objects on the table',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10176','overlay','overlaid','overlaid','덮어씌우다, 더하다',NULL,NULL,NULL,NULL,NULL,'I might have overpaid her in cash',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10177','overpay','overpaid','overpaid','초과 지급하다',NULL,NULL,NULL,NULL,NULL,'My vote got overridden',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10178','override','overrode','overridden','기각하다',NULL,NULL,NULL,NULL,NULL,'The area was overrun with lanterns for the festival',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10179','overrun','overran','overrun','급속히 퍼지다, 초과하다',NULL,NULL,NULL,NULL,NULL,'The director oversaw the concert from the sound booth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10180','oversee','oversaw','overseen','감독하다',NULL,NULL,NULL,NULL,NULL,'He oversold the product to the customer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10181','oversell','oversold','oversold','초과해서 팔다, 부풀려 말하다',NULL,NULL,NULL,NULL,NULL,'I oversew the patch on the piece of cloth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10182','oversew','oversewed','oversewn / oversewed','휘갑치다',NULL,NULL,NULL,NULL,NULL,'The archer overshot the arrow across the field',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10183','overshoot','overshot','overshot','더 가다, 더 많이 하다',NULL,NULL,NULL,NULL,NULL,'I couldn''t hear the alarm because I overslept',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10184','oversleep','overslept','overslept','너무 자다, 늦잠 자다',NULL,NULL,NULL,NULL,NULL,'I regret talking too much over the phone; I feel like I overspoke',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10185','overspeak','overspoke','overspoken','너무 말하다',NULL,NULL,NULL,NULL,NULL,'I realized I overspent this month, while reviewing my monthly expenses',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10186','overspend','overspent','overspent','너무 많이 쓰다, 초과 지출하다',NULL,NULL,NULL,NULL,NULL,'The candy overspilled all over the table',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10187','overspill','overspilled / overspilt','overspilled / overspilt','넘처 흐르다',NULL,NULL,NULL,NULL,NULL,'She was overtaken by her fear of clowns',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10188','overtake','overtook','overtaken','추월하다, 앞지르다',NULL,NULL,NULL,NULL,NULL,'She overthought about the problem',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10189','overthink','overthought','overthought','너무 많이/깊게 생각하다',NULL,NULL,NULL,NULL,NULL,'The king was overthrown by his people',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10190','overthrow','overthrew','overthrown','타도하다',NULL,NULL,NULL,NULL,NULL,'The guitar string was overwound',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10191','overwind','overwound','overwound','너무 감다',NULL,NULL,NULL,NULL,NULL,'She overwrote ideas on the poster',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10192','overwrite','overwrote','overwritten','겹쳐 쓰다',NULL,NULL,NULL,NULL,NULL,'As a soccer player, it is his dream to partake in the World Cup someday',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10193','partake','partook','partaken','참가하다',NULL,NULL,NULL,NULL,NULL,'We already paid for the hotel room',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10194','pay','paid','paid','지불하다',NULL,NULL,NULL,NULL,NULL,'The criminal plead for mercy during the court trial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10195','plead','pleaded / pled','pleaded / pled','애원하다',NULL,NULL,NULL,NULL,NULL,'The structure of the house was prebuilt',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10196','prebuild','prebuilt','prebuilt','이미 지어진 것',NULL,NULL,NULL,NULL,NULL,'The food for the buffet was premade earlier that day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10197','premake','premade','premade','이미 만들어져 있는것',NULL,NULL,NULL,NULL,NULL,'I prepaid for the item online',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10198','prepay','prepaid','prepaid','선납하다',NULL,NULL,NULL,NULL,NULL,'He presold his car because he had to leave town in a hurry',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10199','presell','presold','presold','사전 선전을 하다',NULL,NULL,NULL,NULL,NULL,'The meal was preset prior to the guests'' arrival',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10200','preset','preset','preset','미리 조정하다',NULL,NULL,NULL,NULL,NULL,'The shirt was preshrunk to fit him perfectly',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10201','preshrink','preshrank','preshrunk','미리 줄어들게 하다',NULL,NULL,NULL,NULL,NULL,'She proofread my essay',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10202','proofread','proofread','proofread','(책의) 교정하다',NULL,NULL,NULL,NULL,NULL,'He wanted to prove that he was stronger than him',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10203','prove','proved','proven / proved','입증하다',NULL,NULL,NULL,NULL,NULL,'He put the bread on the table',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10204','put','put','put','놓다',NULL,NULL,NULL,NULL,NULL,'I put the quick-frozen berries on my sandwich',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10205','quick-freeze','quick-froze','quick-frozen','급속 냉동시키다',NULL,NULL,NULL,NULL,NULL,'I want to quit my job and forget about all the work I had left',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10206','quit','quit / quitted','quit / quitted','그만두다',NULL,NULL,NULL,NULL,NULL,'I read the book from cover to cover',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10207','read','read (sounds like "red")','read (sounds like "red")','읽다',NULL,NULL,NULL,NULL,NULL,'I reawoke to the smell of coffee',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10208','reawake','reawoke','reawaken','다시 깨다',NULL,NULL,NULL,NULL,NULL,'I rebid on the play',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10209','rebid','rebid','rebid','재입찰하다',NULL,NULL,NULL,NULL,NULL,'I rebound the notebooks to make it more organized',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10210','rebind','rebound','rebound','다시 묶다',NULL,NULL,NULL,NULL,NULL,'The show was rebroadcasted through the week',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10211','rebroadcast','rebroadcast / rebroadcasted','rebroadcast / rebroadcasted','재방송하다',NULL,NULL,NULL,NULL,NULL,'The architects had to come up with a new plan to rebuild the building',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10212','rebuild','rebuilt','rebuilt','다시 조립하다',NULL,NULL,NULL,NULL,NULL,'The team recast the actors for the upcoming movie',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10213','recast','recast','recast','재구성하다',NULL,NULL,NULL,NULL,NULL,'Are you going to recut it?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10214','recut','recut','recut','다시 자르다',NULL,NULL,NULL,NULL,NULL,'The dealer redealt the cards because he made a mistake',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10215','redeal','redealt','redealt','다시 돌리다',NULL,NULL,NULL,NULL,NULL,'I had to redo my schedule for the week',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10216','redo','redid','redone','다시 하다',NULL,NULL,NULL,NULL,NULL,'I redrew the pattern on my sketchbook',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10217','redraw','redrew','redrawn','다시 그리다',NULL,NULL,NULL,NULL,NULL,'The mechanic refitted the parts of the engine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10218','refit (replace parts)','refit / refitted','refit / refitted','다시 수리하다',NULL,NULL,NULL,NULL,NULL,'I got refitted for my suit',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10219','refit (retailor)','refitted / refit','refitted / refit','다시 맞추다',NULL,NULL,NULL,NULL,NULL,'The barista reground the coffee beans',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10220','regrind','reground','reground','다시 갈다',NULL,NULL,NULL,NULL,NULL,'The flowers regrew once it was spring',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10221','regrow','regrew','regrown','다시 기르다, 재성장하다',NULL,NULL,NULL,NULL,NULL,'We rehung the ornaments on the tree once it was Christmas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10222','rehang','rehung','rehung','다시 걸다',NULL,NULL,NULL,NULL,NULL,'She reheard the song to understand the lyrics better',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10223','rehear','reheard','reheard','다시 듣다',NULL,NULL,NULL,NULL,NULL,'She reknitted the sweater to make it better',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10224','reknit','reknitted / reknit','reknitted / reknit','다시 짜다',NULL,NULL,NULL,NULL,NULL,'He relaid his personal belongings next to him',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10225','relay (for example tiles)','relaid','relaid','다시 두다/ 깔다',NULL,NULL,NULL,NULL,NULL,'Did you relay the message?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10226','relay (pass along) REGULAR','relayed','relayed','전달하다',NULL,NULL,NULL,NULL,NULL,'I need to relearn the materials because I failed the course',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10227','relearn','relearned / relearnt','relearned / relearnt','다시 배우다',NULL,NULL,NULL,NULL,NULL,'They relit the room at night',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10228','relight','relit / relighted','relit / relighted','다시 (불을) 켜다',NULL,NULL,NULL,NULL,NULL,'The glass was remade in the workshop',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10229','remake','remade','remade','다시 만들다',NULL,NULL,NULL,NULL,NULL,'He repaid what he owed to me in cash',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10230','repay','repaid','repaid','갚다, 보답하다',NULL,NULL,NULL,NULL,NULL,'She reread the book so many times that she could repeat the exact lines in the book',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10231','reread','reread','reread','다시 읽다, 재독하다',NULL,NULL,NULL,NULL,NULL,'The television network reran the show over and over again',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10232','rerun','reran','rerun','반복하다, 재상영 하다',NULL,NULL,NULL,NULL,NULL,'The owner resold the house',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10233','resell','resold','resold','되팔다',NULL,NULL,NULL,NULL,NULL,'Did you resend the text message?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10234','resend','resent','resent','다시 보내다, 재발송하다',NULL,NULL,NULL,NULL,NULL,'I reset my laptop',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10235','reset','reset','reset','재설정하다',NULL,NULL,NULL,NULL,NULL,'The shirt has been resewn by the seamstress',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10236','resew','resewed','resewn / resewed','다시 꿰매다',NULL,NULL,NULL,NULL,NULL,'The photographer retook the image',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10237','retake','retook','retaken','탈환하다',NULL,NULL,NULL,NULL,NULL,'The teacher retaught the students on how to solve the problem',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10238','reteach','retaught','retaught','재교육하다',NULL,NULL,NULL,NULL,NULL,'The jeans were retorn and made into a new style',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10239','retear','retore','retorn','다시 찢다',NULL,NULL,NULL,NULL,NULL,'He retold her the story',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10240','retell','retold','retold','다시 말하다',NULL,NULL,NULL,NULL,NULL,'He rethought his entire plan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10241','rethink','rethought','rethought','다시 생각하다',NULL,NULL,NULL,NULL,NULL,'He retread his footsteps',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10242','retread','retread','retread','되밟아 가다, 다시 밟다',NULL,NULL,NULL,NULL,NULL,'The technician retrofitted the computer system',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10243','retrofit','retrofitted / retrofit','retrofitted / retrofit','새로 장착하다',NULL,NULL,NULL,NULL,NULL,'I rewoke to the sound of the alarm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10244','rewake','rewoke / rewaked','rewaken / rewaked','다시 꺠어나다',NULL,NULL,NULL,NULL,NULL,'I rewore the sweater from yesterday',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10245','rewear','rewore','reworn','다시 입다',NULL,NULL,NULL,NULL,NULL,'The basket was rewoven',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10246','reweave','rewove / reweaved','rewoven / reweaved','다시 짜다, 재결합하다',NULL,NULL,NULL,NULL,NULL,'The couple recently rewed',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10247','rewed','rewed / rewedded','rewed / rewedded','재혼하다',NULL,NULL,NULL,NULL,NULL,'He rewet himself to avoid the heat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10248','rewet','rewet / rewetted','rewet / rewetted','다시 젖다, 적시다',NULL,NULL,NULL,NULL,NULL,'He rewon the match against his opponent',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10249','rewin','rewon','rewon','다시 획득하다, 되찾다',NULL,NULL,NULL,NULL,NULL,'I rewound the cassette tape',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10250','rewind','rewound','rewound','되감다',NULL,NULL,NULL,NULL,NULL,'She rewrote the story from the beginning',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10251','rewrite','rewrote','rewritten','다시 쓰다',NULL,NULL,NULL,NULL,NULL,'I would like to get rid of all that trash',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10252','rid','rid','rid','~을 없애다, 제거하다',NULL,NULL,NULL,NULL,NULL,'They rode on the motorcycle together',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10253','ride','rode','ridden','타다',NULL,NULL,NULL,NULL,NULL,'She rang the bell',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10254','ring','rang','rung','울리다',NULL,NULL,NULL,NULL,NULL,'The sun rose from the east',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10255','rise','rose','risen','증가하다; (위로) 뜨다',NULL,NULL,NULL,NULL,NULL,'The exterior of the building was old and roughcast',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10256','roughcast','roughcast','roughcast','건물 외별을 초벽칠하다',NULL,NULL,NULL,NULL,NULL,'The boy ran all the way to home plate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10257','run','ran','run','달리다',NULL,NULL,NULL,NULL,NULL,'The construction workers use a sand-cast system',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10258','sand-cast','sand-cast','sand-cast','모래 거푸집에서 만들다',NULL,NULL,NULL,NULL,NULL,'He sawed the wood in half',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10259','saw','sawed','sawed / sawn','톱질하다',NULL,NULL,NULL,NULL,NULL,'Can you tell me what he said?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10260','say','said','said','말하다',NULL,NULL,NULL,NULL,NULL,'She saw the view from far away',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10261','see','saw','seen','보다, 보이다',NULL,NULL,NULL,NULL,NULL,'He sought a way to escape',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10262','seek','sought','sought','구하다, 찾다, 추구하다',NULL,NULL,NULL,NULL,NULL,'I wonder if I should sell my stocks',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10263','sell','sold','sold','팔다',NULL,NULL,NULL,NULL,NULL,'Did you send the text?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10264','send','sent','sent','보내다',NULL,NULL,NULL,NULL,NULL,'She helped set the dinner table',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10265','set','set','set','놓다',NULL,NULL,NULL,NULL,NULL,'He sewed all day to make a living',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10266','sew','sewed','sewn / sewed','바느질하다, 꿰매다',NULL,NULL,NULL,NULL,NULL,'They shook hands',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10267','shake','shook','shaken','흔들다',NULL,NULL,NULL,NULL,NULL,'He shaved his hair off',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10268','shave','shaved','shaved / shaven','면도하다',NULL,NULL,NULL,NULL,NULL,'Sheeps are sheared for wool',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10269','shear','sheared','sheared / shorn','(머리/ 털을) 깍다',NULL,NULL,NULL,NULL,NULL,'The baby shed tears because he missed his mom',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10270','shed','shed','shed','흘리다, 저절로 떨어지게 하다',NULL,NULL,NULL,NULL,NULL,'The light shined through the trees',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10271','shine','shined / shone','shined / shone','빛나다, 비추다',NULL,NULL,NULL,NULL,NULL,'He shot the target right on point',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10272','shoot','shot','shot','쏘다',NULL,NULL,NULL,NULL,NULL,'She showed her how to do the job',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10273','show','showed','shown / showed','보여 주다',NULL,NULL,NULL,NULL,NULL,'Her height shrunk as she aged',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10274','shrink','shrank / shrunk','shrunk','줄어들게 하다, 줄어들다',NULL,NULL,NULL,NULL,NULL,'Can you please shut the door?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10275','shut','shut','shut','덮다, 닫다',NULL,NULL,NULL,NULL,NULL,'Can you sight-read music?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10276','sight-read','sight-read','sight-read','악보를 처음 보고 즉석에서 노래하다; 연습하지 않고 읽기',NULL,NULL,NULL,NULL,NULL,'He sang his heart out at the concert',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10277','sing','sang','sung','노래하다',NULL,NULL,NULL,NULL,NULL,'She sank to the bottom of the ocean',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10278','sink','sank / sunk','sunk','가라앉다',NULL,NULL,NULL,NULL,NULL,'They sat next to each other',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10279','sit','sat','sat','앉다',NULL,NULL,NULL,NULL,NULL,'The knight will slay the enemy',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10280','slay (kill)','slew / slayed','slain / slayed','죽이다, 살인하다',NULL,NULL,NULL,NULL,NULL,'She slept with her stuffed animal',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10281','slay (amuse) REGULAR','slayed','slayed','즐겁게 하다, 감명을 주다',NULL,NULL,NULL,NULL,NULL,'He slid to the base before being tagged',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10282','sleep','slept','slept','자다',NULL,NULL,NULL,NULL,NULL,'She slung the backpack over her shoulders',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10283','slide','slid','slid','미끄러지다',NULL,NULL,NULL,NULL,NULL,'She slinked out of the room so that no one would notice her',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10284','sling','slung','slung','던지다, 매다',NULL,NULL,NULL,NULL,NULL,'Be careful no to slit his throat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10285','slink','slinked / slunk','slinked / slunk','살금살금 움직이다',NULL,NULL,NULL,NULL,NULL,'She stopped to smell the roses',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10286','slit','slit','slit','길게 자르다',NULL,NULL,NULL,NULL,NULL,'He tried to sneak out',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10287','smell','smelled / smelt','smelled / smelt','냄새가 나다',NULL,NULL,NULL,NULL,NULL,'He sowed some seeds in his garden',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10288','sneak','sneaked / snuck','sneaked / snuck','살금살금 가다, 몰래 하다',NULL,NULL,NULL,NULL,NULL,'Will you speak at the forum tonight?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10289','sow','sowed','sown / sowed','뿌리다, 심다',NULL,NULL,NULL,NULL,NULL,'The racer sped up to the finish line',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10290','speak','spoke','spoken','말하다',NULL,NULL,NULL,NULL,NULL,'Can you spell "carpe diem" for me?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10291','speed','sped / speeded','sped / speeded','속도를 내다',NULL,NULL,NULL,NULL,NULL,'I spent a lot of money today',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10292','spell','spelled / spelt','spelled / spelt','철자를 말하다',NULL,NULL,NULL,NULL,NULL,'He spilled juice all over the place',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10293','spend','spent','spent','쓰다',NULL,NULL,NULL,NULL,NULL,'He spun the record on the turntable',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10294','spill','spilled / spilt','spilled / spilt','흘리다, 쏟다',NULL,NULL,NULL,NULL,NULL,'The performer spit fire from his mouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10295','spin','spun','spun','돌다, 회전하다',NULL,NULL,NULL,NULL,NULL,'The road split in two',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10296','spit','spit / spat','spit / spat','뱉다, 내뱉다',NULL,NULL,NULL,NULL,NULL,'The milk was spoiled',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10297','split','split','split','나누다, 분열시키다',NULL,NULL,NULL,NULL,NULL,'The mother spoon-fed the baby',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10298','spoil','spoiled / spoilt','spoiled / spoilt','망치다, 버려 놓다',NULL,NULL,NULL,NULL,NULL,'I spread some avocado on my toast',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10299','spoon-feed','spoon-fed','spoon-fed','솓가락으로 일일이 떠먹여 주다',NULL,NULL,NULL,NULL,NULL,'The squirrel sprung out of nowhere',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10300','spread','spread','spread','펼치다',NULL,NULL,NULL,NULL,NULL,'They stood in line',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10301','spring','sprang / sprung','sprung','휙 나타나다, 갑자기 튀어나오다',NULL,NULL,NULL,NULL,NULL,'The kid tried to steal some strawberries',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10302','stand','stood','stood','서다, 일어서다',NULL,NULL,NULL,NULL,NULL,'There was gum stuck to his shoes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10303','steal','stole','stolen','훔치다',NULL,NULL,NULL,NULL,NULL,'The bee stung me',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10304','stick','stuck','stuck','붙이다, 달라붙다',NULL,NULL,NULL,NULL,NULL,'He stinks because he hasn''t washed in a long time',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10305','sting','stung','stung','쏘다 찌르다',NULL,NULL,NULL,NULL,NULL,'The sand strewed from my fingertips',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10306','stink','stunk / stank','stunk','냄새가 나다, 악취가 풍기다',NULL,NULL,NULL,NULL,NULL,'He strode across the sidewalk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10307','strew','strewed','strewn / strewed','흩다, 흩어지다',NULL,NULL,NULL,NULL,NULL,'I will strike the wrong answers out',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10308','stride','strode','stridden','성큼성큼 걷다',NULL,NULL,NULL,NULL,NULL,'The baseball player struck out',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10309','strike (delete)','struck','stricken','삭제하다',NULL,NULL,NULL,NULL,NULL,'There were lanterns strung in the middle of the street',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10310','strike (hit)','struck','struck / stricken','치다',NULL,NULL,NULL,NULL,NULL,'They strove to the finish line',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10311','string','strung','strung','달다, 매달다',NULL,NULL,NULL,NULL,NULL,'I sublet my apartment to another student over the summer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10312','strive','strove / strived','striven / strived','분투하다',NULL,NULL,NULL,NULL,NULL,'He was sunburnt from the strong sun rays',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10313','sublet','sublet','sublet','전대하다',NULL,NULL,NULL,NULL,NULL,'I can''t help but swear because I''m so angry',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10314','sunburn','sunburned / sunburnt','sunburned / sunburnt','햇별에 심하게 타다',NULL,NULL,NULL,NULL,NULL,'He sweated from working out',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10315','swear','swore','sworn','욕을 하다',NULL,NULL,NULL,NULL,NULL,'He swept the floors',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10316','sweat','sweat / sweated','sweat / sweated','땀을 흘리다',NULL,NULL,NULL,NULL,NULL,'The balloon swelled up with air',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10317','sweep','swept','swept','쓸다',NULL,NULL,NULL,NULL,NULL,'She swam everyday',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10318','swell','swelled','swollen / swelled','붓다, 부어오르다',NULL,NULL,NULL,NULL,NULL,'She swung the bat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10319','swim','swam','swum','수영하다, 헤엄치다',NULL,NULL,NULL,NULL,NULL,'She took some pictures during her vacation',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10320','swing','swung','swung','흔들리다, 빙 돌다',NULL,NULL,NULL,NULL,NULL,'He taught his friend how to solve the problem',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10321','take','took','taken','가지고 가다',NULL,NULL,NULL,NULL,NULL,'He tore the sheet',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10322','teach','taught','taught','가르키다',NULL,NULL,NULL,NULL,NULL,'They telecast the game live',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10323','tear','tore','torn','찢다',NULL,NULL,NULL,NULL,NULL,'My colleague told me that he might quit the job',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10324','telecast','telecast','telecast','방영하다, 텔레비전 방송을 하다',NULL,NULL,NULL,NULL,NULL,'The customer test-drove the car',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10325','tell','told','told','말하다, 알려 주다',NULL,NULL,NULL,NULL,NULL,'He test-flew the airplane',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10326','test-drive','test-drove','test-driven','시운정하다',NULL,NULL,NULL,NULL,NULL,'She thought about it for a second',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10327','test-fly','test-flew','test-flown','시험 비행을 하다',NULL,NULL,NULL,NULL,NULL,'The pitcher threw the ball hard',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10328','think','thought','thought','생각하다',NULL,NULL,NULL,NULL,NULL,'She thrust her leg up',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10329','throw','threw','thrown','던지다',NULL,NULL,NULL,NULL,NULL,'He tread into unknow territory',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10330','thrust','thrust','thrust','밀다, 밀치다, 찌르다',NULL,NULL,NULL,NULL,NULL,'He troubleshot the error',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10331','tread','trod','trodden / trod','디디다, 밟다',NULL,NULL,NULL,NULL,NULL,'They typecast him as the bad boy',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10332','troubleshoot','troubleshot','troubleshot','고장 수리원의 역할을 하다',NULL,NULL,NULL,NULL,NULL,'The formula is typeset in the system',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10333','typecast','typecast','typecast','고정된 배역을 맡기다',NULL,NULL,NULL,NULL,NULL,'The author typewrote the book',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10334','typeset','typeset','typeset','식자하다, 조판하다',NULL,NULL,NULL,NULL,NULL,'Can you unbend from that position?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10335','typewrite','typewrote','typewritten','타이프라이터로 치다',NULL,NULL,NULL,NULL,NULL,'I''ll try to unbind the knot in the rope',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10336','unbend','unbent','unbent','펴다, 긴장을 풀다',NULL,NULL,NULL,NULL,NULL,'She feels free when unclothed',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10337','unbind','unbound','unbound','풀다, 끄르다',NULL,NULL,NULL,NULL,NULL,'I underbid on the bet',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10338','unclothe','unclothed / unclad','unclothed / unclad','옷을 벗기다',NULL,NULL,NULL,NULL,NULL,'I was able to buy the house for cheap because the owner undercut the price',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10339','underbid','underbid','underbid','~보다 낮은 가격을 부르다',NULL,NULL,NULL,NULL,NULL,'The dog was skinny because it was underfed',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10340','undercut','undercut','undercut','~보다 저가로 팔다',NULL,NULL,NULL,NULL,NULL,'He underwent major surgery',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10341','underfeed','underfed','underfed','충분한 음식을 주지 않다',NULL,NULL,NULL,NULL,NULL,'There was a more serious matter that underlay the issue',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10342','undergo','underwent','undergone','안 좋은 일 등을 겪다',NULL,NULL,NULL,NULL,NULL,'I undersold my furniture because I had to move to a new place fast',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10343','underlie','underlay','underlain','기저를 이루다',NULL,NULL,NULL,NULL,NULL,'I was able to save some money since I underspent my allowance this month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10344','undersell','undersold','undersold','싼 가격에 팔다',NULL,NULL,NULL,NULL,NULL,'We understood each other well',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10345','underspend','underspent','underspent','돈을 덜 쓰다',NULL,NULL,NULL,NULL,NULL,'I agree to undertake full responsibility of this project',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10346','understand','understood','understood','이해하다',NULL,NULL,NULL,NULL,NULL,'Are you willing to underwrite?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10347','undertake','undertook','undertaken','(책임을 맡아서) 착수하다',NULL,NULL,NULL,NULL,NULL,'Can you undo the knot?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10348','underwrite','underwrote','underwritten','보험을 인수하다, 빛 보증을 서다',NULL,NULL,NULL,NULL,NULL,'The ocean was beginning to unfreeze as the weather got warmer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10349','undo','undid','undone','풀다, 원상태로 돌리다',NULL,NULL,NULL,NULL,NULL,'You should unhang the wreath from the door once Christmas is over',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10350','unfreeze','unfroze','unfrozen','녹이다, 해동되다',NULL,NULL,NULL,NULL,NULL,'He finally revealed the secret and unhid the truth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10351','unhang','unhung','unhung','내려 놓다',NULL,NULL,NULL,NULL,NULL,'I wanted to unknit the scarf and start again',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10352','unhide','unhid','unhidden','감췄던 것을 드러낸다, 알리다',NULL,NULL,NULL,NULL,NULL,'Why would you want to unlearn something you worked so hard to learn?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10353','unknit','unknitted / unknit','unknitted / unknit','펴다, 풀리다',NULL,NULL,NULL,NULL,NULL,'I unsewed the stitches on the clothes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10354','unlearn','unlearned / unlearnt','unlearned / unlearnt','배운 것을 고의적으로 잊다',NULL,NULL,NULL,NULL,NULL,'The acrobats unslung from the ropes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10355','unsew','unsewed','unsewn / unsewed','실밥을 뽑다, 풀다',NULL,NULL,NULL,NULL,NULL,'Did it unspun by itself?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10356','unsling','unslung','unslung','매단 곳에서 풀다',NULL,NULL,NULL,NULL,NULL,'The puzzle pieces were unstuck',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10357','unspin','unspun','unspun','되돌리다',NULL,NULL,NULL,NULL,NULL,'I''m going to unstring this spool',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10358','unstick','unstuck','unstuck','잡아떼다 (붙어 있던 것을 떼다)',NULL,NULL,NULL,NULL,NULL,'The basket is becoming unwoven',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10359','unstring','unstrung','unstrung','(현을/실을) 풀다',NULL,NULL,NULL,NULL,NULL,'Make sure you unwind that rope',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10360','unweave','unwove / unweaved','unwoven / unweaved','(짠 것을) 풀다',NULL,NULL,NULL,NULL,NULL,'I want to uphold my exercise routine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10361','unwind','unwound','unwound','(감긴 것을) 풀다; 긴장을 풀다',NULL,NULL,NULL,NULL,NULL,'I''m really upset today',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10362','uphold','upheld','upheld','유지시키다',NULL,NULL,NULL,NULL,NULL,'The memory of the past still vexed her',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10363','upset','upset','upset','속상하게 만들다',NULL,NULL,NULL,NULL,NULL,'I woke up just on time',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10364','vex','vext / vexed','vext / vexed','성가시게하다',NULL,NULL,NULL,NULL,NULL,'The townspeople were waylaid by the military troops',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10365','wake','woke / waked','woken / waked','깨우다',NULL,NULL,NULL,NULL,NULL,'I wore a similar shirt as my friend',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10366','waylay','waylaid','waylaid','불러 세우다',NULL,NULL,NULL,NULL,NULL,'They mainly sell woven baskets',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10367','wear','wore','worn','입고 있다',NULL,NULL,NULL,NULL,NULL,'The couple finally wed',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10368','weave','wove / weaved','woven / weaved','짜서 만들다',NULL,NULL,NULL,NULL,NULL,'She wept in sorrow',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10369','wed','wed / wedded','wed / wedded','혼인하다',NULL,NULL,NULL,NULL,NULL,'She got wet at the beach',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10370','weep','wept','wept','울다, 눈물을 흘리다',NULL,NULL,NULL,NULL,NULL,'She won the race',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10371','wet','wet / wetted','wet / wetted','젖다',NULL,NULL,NULL,NULL,NULL,'I wound the yarn into a ball',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10372','whet  REGULAR','whetted','whetted','(욕구/흥미를) 돋우다',NULL,NULL,NULL,NULL,NULL,'I withdrew some money',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10373','win','won','won','이기다',NULL,NULL,NULL,NULL,NULL,'I withheld my opinion',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10374','wind','wound','wound','(실 등을) 감다',NULL,NULL,NULL,NULL,NULL,'I withstood the pain',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10375','withdraw','withdrew','withdrawn','물러나다, 철수하다',NULL,NULL,NULL,NULL,NULL,'I wrapped the gift',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10376','withhold','withheld','withheld','주지 않다',NULL,NULL,NULL,NULL,NULL,'He wreaked havoc by not throwing the trash away',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10377','withstand','withstood','withstood','견뎌 내다',NULL,NULL,NULL,NULL,NULL,'I''d like to wring his neck because he''s so annoying',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10378','wrap','wrapped / wrapt','wrapped / wrapt','포장하다',NULL,NULL,NULL,NULL,NULL,'I wrote in my journal',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10379','wreak','wreaked','wreaked / wroken','(큰 피해 등을) 입히다',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10380','wring','wrung','wrung','(빨래를) 짜다; 비틀다',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "test" VALUES ('10381','write','wrote','written','쓰다, 작성하다',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
COMMIT;
